\documentclass{article}
\usepackage[top=0.5in,left=0.7in]{geometry}
\title{Notes 2}

\usepackage{tabularx}

\usepackage{amsmath}
\usepackage{natbib}
\usepackage{hyperref}
\bibliographystyle{chicago}
\date{\today}

\begin{document}

\maketitle

Let's try to think about this more generally. We want to design and experiment for red queen hypothesis and perform power analysis.

\section{Empirical studies}

\begin{table}[h]
\centering
\begin{tabularx}{\textwidth}{XXXXX}
\hline
Study & Host & Parasite & Experiment & Notes\\
\hline
\cite{michiels2001parthenogenetic} - Lab & Flatworm \textit{Schmidtea polychroa} - obligate sexual diploid and parthenogenetic triploid & Amoeboid protozoan (Asexual) & Compare proportion of infected individuals in mixed samples with LRT; rate of infection & Highly heterogeneous spatial distribution; need longer study\\
\cite{kumpulainen2004parasites} - Field & psychid moth & hymenopteran parasitoids & test prevalence of parasitoids and prevalence of sexual reproduction & demonstrates cost of sex; no evidence for different reproduction mode preferring different space\\
\cite{ben2005spatial} - Field & snails & trematodes & correlation for males and frequency of infection & Male frequencies decreased bu infection levels increased\\
\cite{bruvo2007synergism} - Field & Planarian flatworm \textit{Schmidtea polychroa} - diploid sexuals and (mostly) triploid parthenogens & only look at asexual; test for infection rates among the clonal lineage; relate parasite load and fertility &\\
\cite{verhoeven2013geographic} - Field & Dandelions - diploid sexual and triploid obligate apomicts & Microbial communities, fungus, and weevil & Experiment + testing infection prevalence in nature & See geographic parthenogenesis; they address that they might have a power problem\\
\cite{vsimkova2013mhc} & Gibel carp - sexual diploid and gynogenetic triploid & metazoan parasites & Comparison of MHC genes: do sexual individuals have higher variability + do asexual invidiauls suffer from higher parasite load & "Coexistence may be maintained by male mate choice or spatial and temporal extinction and recolonization"; need longer study \\
\cite{auld2016sex} - Lab & Daphnia - partly sexual and asexual & \textit{Pasteuria ramosa} & Time shift experiment (testing for proportion of infected and spores per host) with MCMCglmm & Unrealistic setting in nature; their study looks at within-host factors \\
\\
\cite{slowinski2016coevolutionary} & \textit{Caenorhabditis elegans} - hermaphrodite and obligate sexual & \textit{Serratia marcescens} & Introduction of mixed mating into outcrossing population and exposing different types of parasites - test selfing rates using ANOVA & parasite has to be coevolving\\
\end{tabularx}
\end{table}

What I should be looking at:

\begin{itemize}
    \item From \cite{auld2016sex}: "heritable component, rapid parasite evolution, and temporally shifting parasite-mediate selection"
\end{itemize}

\subsection{Not Red queen?}

\begin{itemize}
    \item \cite{michiels2001parthenogenetic} says that their system does not match requirements of the red queen hypothesis (weak infection fitness cost). They think that there might be other factors involved.
\end{itemize}

\section{Model}

\subsection{Notes}

\cite{michiels2001parthenogenetic}: heterozygote triploids are hard to distinguish so di-allelic representation is used

\cite{lively2001trematode} suggests that prevalence is actually not a good measure. Risk of infection (probability of exposure to ifective parasite propagules) is a better measure. Near the \emph{switch point}, asexuals can have higher prevalence but this range is fairly narrow.

\cite{hakoyama2004coexistence} tried to model Japanese crucian carp and showed that parasitism may explain the evolution of sex. They also show that coexistence of parthnogenetic complex is more likely than that of gynogenetic complex. Read this paper later to see how we want to analyze our model!

\cite{neiman2017sex} emphasizes importance of a pluralist approach and suggests directions. It's worth noting that many of pluralist studies include red queen dynamics. We are being a pluralist because we're adding ecological feedback in the model. I don't think we have to test for power yet as there aren't many appropriate systems but it might still be important and interesting to compare power for pluralist idea vs. red queen alone. See \cite{meirmans2006methodologies} for testing interactive effects.

\cite{agrawal2002infection} says that dynamical qualities of matching alleles model can be observed across other continuum. We can just stick with MA for now.

\cite{agrawal2009differences} says GFG model failed to show selection for sex or recombination in diploid model. In MA and IMA models, recombination was often more favored than sex. However, they also saw cases where sex was favored but recombination was not. Using a haploid model can be misleading.

\subsection{Deterministic model}

We simulate red queen dynamics based on matching alleles (MA) model using diploid hosts and haploid parasites. Instead of using modifier genes, we model obligate asexual and sexual population explicitly. Assuming there are two biallelic loci, there are four types of gametes that can be produced: $AB, Ab, aB, ab$. 
We will be using indices $1-4$ for simplicity to refer to these gametes \citep{agrawal2006host}.

Let $A_{ij}$ and $S_{ij}$ represent density of susceptible asexual and sexual population with genotype $ij$.
Following \cite{lively2010epidemiological}, we can write
$$
\begin{aligned}
S_{ii}' &= (1-s) S_0 (g_i^2) [W_I P_{ij} + W_U(1-P_{ij})],\\
S_{ij}' &= (1-s) S_0 (2 g_i g_j) [W_I P_{ij} + W_U(1-P_{ij})],\\
A_{ij}' &= A_{ij} [W_I P_{ij} + W_U (1-P_{ij})],
\end{aligned}
$$
where $s$ is the proportion of male offspring produced, $S_0$ is the total density of the susceptible sexual population, $g_i$ is the frequency of gamete $i$ before recombination and $P_{ij}$ is the probability of infection. $W_I$ and $W_U$ are modeled in the same way as \cite{lively2010epidemiological}. After recombination, $\mu$ individuals enter all sexual genotypes.

Following selection, we assume that parasites can go under mutation before infecting susceptible hosts. Following the approach by \cite{ashby2015diversity}, we can find the density of parasite with genotype $i$:
$$
I_i = \frac{1}{2} \left((1-\epsilon) \sum_{p} \delta_{ip} (S_{ip,I} + A_{ip,I})  + \frac{\epsilon}{n} \sum_{p, q} \eta_{ip} (S_{pq,I} + A_{pq,I}) \right) + \kappa.
$$

$P_{ij}$ cannot be modeled in the same way as \cite{lively2010epidemiological} because we're assuming diploid hosts. Thus, we write
$$
P_{ij} = 1 - \exp(-\beta(I_i + I_j)/N').
$$

\bibliography{redqueen}
\end{document}
