\documentclass{article}
\title{Document for USRA}

\usepackage{tabularx}

\usepackage{amsmath}
\usepackage{natbib}
\usepackage{hyperref}
\bibliographystyle{chicago}
\date{\today}

\begin{document}

\maketitle

\section{Methods}

\subsection{Model}

%% Although natural systems that have been studied under the context of the Red Queen Hypothesis often contains polyploid asexuals \citep{dybdahl1995diverse, michiels2001parthenogenetic, ben2005spatial, bruvo2007synergism, verhoeven2013geographic, vsimkova2013mhc}, we do not consider polyploidy for simplicity.

We model obligate sexual hosts competing with obligate asexual hosts based on the model introduced by \cite{lively2010epidemiological}.
Whereas most mathematical models used in the context of evolution of sex study population in a theoretical setting, \cite{lively2010epidemiological} explicitly models epidemiological and ecological structure, making it a suitable candidate for modeling a natural population \cite{ashby2015diversity}.
We further extend the model by adding a spatial structure and stochasticity.

All hosts are assumed to be diploids with two biallelic loci, and parasites are assumed to be haploids. For convenience, we use indices $1-4$ to refer to following haplotypes \citep{agrawal2006host}. For example, an individual with genotype $12$ has haplotypes $AB$ and $Ab$ and an arbitrty genotype is denoted as $ij$.

Let $S_{ij}^k(t)$ and $A_{ij}^k(t)$ be the number of sexual and asexual hosts with genotype $ij$ in site $k$ at generation $t$. 
For simplicity, we drop the superscript representing sites and write $S_{ij}(t)$ and $A_{ij}(t)$, unless denoted otherwise. 
Following \cite{lively2010epidemiological}, the expected number of sexual offsprings (without recombination or outcrossing) produced in the next generation by hosts from a single site is given by
\begin{equation}
S_{ij}' = (1-s) \left(W_U S_{ij,U} (t) + W_I S_{ij,I} (t)\right),
\end{equation}
where $s$ is the proportion of males produced. $S_{ij, U}$ and $S_{ij,I}$ represent the number of uninfected and infected sexual hosts in site $k$, respectively and $W_U$ and $W_I$ are their corresponding fitnesses.

Let $g_i$ be the expected number of gametes with haplotype $i$ passed on to the next generation by sexual hosts from a single site:
\begin{equation}
\begin{aligned}
g_1 &= \sum_{j=1}^4 \delta_{1j} S_{1j}' - r S_{14}' + r S_{23}', \\
g_2 &= \sum_{j=1}^4 \delta_{2j} S_{2j}' - r S_{23}' + r S_{14}', \\
g_3 &= \sum_{j=1}^4 \delta_{3j} S_{3j}' - r S_{23}' + r S_{14}', \\
g_4 &= \sum_{j=1}^4 \delta_{4j} S_{4j}' - r S_{14}' + r S_{23}',
\end{aligned}
\end{equation}
where $r$ is the recombination probability.
After recombination and outcrossing, the expected the number of sexual offsprings with genotype $ij$ produced in the next generation by hosts from a single site can be written as
\begin{equation}
S_{ij}'' = \frac{(1- \delta_{ij}) g_i g_j}{2 \sum_k g_k},
\end{equation}
where $\delta_{ij}$ is the Kronecker-delta.

We assume that a population distribution $\epsilon \cdot 100 \%$ of its offsprings to other sites evenly. Then, the expected number of sexual offspring with genotype $ij$ in the next generation (accounting for contributions from all sites) is given by
\begin{equation}
\mathrm{E}\left(S_{ij}^k(t+1)\right) = (1 - \epsilon_{\textrm{site}}) \left(S_{ij}^k\right)'' + \frac{\epsilon_{\textrm{site}}}{n_\textrm{site}-1} \sum_{l \neq k} \left(S_{ij}^l\right)''.
\end{equation}
We then take a poisson random variable to simulate process error and allow for stochastic migration to avoid fixation:
\begin{equation}
S_{ij}^k(t+1) \sim \mathrm{Poisson}\left(\lambda=\mathrm{E}\left(S_{ij}^k(t+1)\right)\right) + \mathrm{Bernoulli}\left(p=p_{\textrm{sex}}\right),
\end{equation}
where $p_\textrm{sex}$ is the probability that a sexual host enters the population.

Asexual hosts are assumed to be strictly clonal. Then, the expected number of asexual offsprints with genotype $ij$ produced in the next generation by hosts from a single site is given by
\begin{equation}
A_{ij}' = W_U A_{ij,U} (t) + W_I A_{ij,I} (t).
\end{equation}
Accounting for contributions from all sites, we get
\begin{equation}
\mathrm{E}\left(A_{ij}^k(t+1)\right) = (1 - \epsilon_{\textrm{site}}) \left(A_{ij}^k\right)' + \frac{\epsilon_{\textrm{site}}}{n_\textrm{site}-1} \sum_{l \neq k} \left(A_{ij}^l\right)'.
\end{equation}
Finally, we take a poisson random variable to obtain the number of asexual offsprings in the next generation and allow for migration:
\begin{equation}
A_{ij}^k(t+1) \sim \mathrm{Poisson}\left(\lambda=\mathrm{E}\left(A_{ij}^k(t+1)\right)\right) + \mathrm{Bernoulli}\left(p=p_{\textrm{asex}}\right),
\end{equation}
where $p_\textrm{asex}$ is the probability that an asexual host enters the population.

To model infection, we combine the approaches by \cite{lively2010epidemiological} and \cite{ashby2015diversity}.
The expected number of infected hosts that carry parasite with genotype $i$ at generation $t$ is given by:
\begin{equation}
I_{i}(t) = \sum_{p} 2^{\delta_{ij}} \left( S_{ip,i,I}(t) + A_{ip,i,I}(t)\right),
\end{equation}
where $S_{ip,i,I}$ and $A_{ip,i,I}$ are the expected number of sexual and asexual hosts infected with genotype $i$ parasite. Following \cite{ashby2015diversity}, we assume that mutation can occur in one locus with probability $\epsilon$. We also allow for migration with probability $p_\textrm{parasite}$ to avoid fixation. Then, the number of infected individuals carrying parasite with genotype $i$ after mutation is given by:
\begin{equation}
\begin{aligned}
I_1' &= (1-\epsilon) I_1 + \frac{\epsilon}{2} \left(I_2 + I_3 \right) + \mathrm{Bernoulli}\left(p=p_{\textrm{parasite}}\right),\\
I_2' &= (1-\epsilon) I_2 + \frac{\epsilon}{2} \left(I_1 + I_4 \right) + \mathrm{Bernoulli}\left(p=p_{\textrm{parasite}}\right),\\
I_3' &= (1-\epsilon) I_3 + \frac{\epsilon}{2} \left(I_1 + I_4 \right) + \mathrm{Bernoulli}\left(p=p_{\textrm{parasite}}\right),\\
I_4' &= (1-\epsilon) I_4 + \frac{\epsilon}{2} \left(I_2 + I_3 \right) + \mathrm{Bernoulli}\left(p=p_{\textrm{parasite}}\right).
\end{aligned}
\end{equation}

Let $\lambda_i^k$ be the poisson mean number of exposures caused by parasites with genotype $i$ from site $k$ in the next generation \cite{lively2010epidemiological}:
\begin{equation}
\lambda_i^k = \frac{\beta^k}{2 N^k(t+1)} I_i',
\end{equation}
where $\beta^k$ represents parasite fecundity at site $k$ \cite{lively2010epidemiological}.
Assuming that infected hosts can also mix with hosts in other sites, the mean number of exposures to parasites with genotype $i$ that a susceptible host in site $k$ receives is
\begin{equation}
\lambda_{i, \textrm{total}}^k = (1 - \epsilon_{\textrm{site}}) \lambda_i^k  + \frac{\epsilon_{\textrm{site}}}{n_\textrm{site}-1} \sum_{l \neq k} \lambda_i^l. 
\end{equation}
Then, a force of infection from parasite $i$ that a susceptible host with genotype $ij$ in site $k$ experiences is
\begin{equation}
\mathrm{FOI}_{ij}^k = \lambda_{i, \textrm{total}}^k + \lambda_{j, \textrm{total}}^k.
\end{equation}
The probability of infection for a host with genotype $ij$ at site $k$ in the next generation is
\begin{equation}
P_{ij}^k(t+1) = 1 - \exp\left(\mathrm{FOI}_{ij}^k\right).
\end{equation}

Finally, the number of infected individuals in the next generation follows a binomial distribution:
\begin{equation}
\begin{aligned}
S_{ij,I}^k (t+1) &\sim \mathrm{Binom}(S_{ij}^k (t+1), P_{ij}^k),\\
A_{ij,I}^k (t+1) &\sim \mathrm{Binom}(A_{ij}^k (t+1), P_{ij}^k).
\end{aligned}
\end{equation}
Expected number of individuals infected with haplotype $i$ in the next generation is given by a ratio of $\lambda$:
\begin{equation}
\begin{aligned}
S_{ij,i,I}^k(t+1) &= \frac{\lambda_{i, \textrm{total}}^k}{\lambda_{i, \textrm{total}}^k + \lambda_{j, \textrm{total}}^k} S_{ij,I}^k(t+1)\\
A_{ij,i,I}^k(t+1) &= \frac{\lambda_{i, \textrm{total}}^k}{\lambda_{i, \textrm{total}}^k + \lambda_{j, \textrm{total}}^k} A_{ij,I}^k(t+1)
\end{aligned}
\end{equation}

\subsection{Simulations}

\subsection{Approximate Bayesian Computation}


\section{Results}

\begin{figure}[!ht]
\includegraphics[width=\textwidth]{../fig/smc_param.pdf}
\caption{{\bf Need caption.}
Need caption}
\label{fig:smcparam}
\end{figure}

\begin{figure}[!ht]
\includegraphics[width=\textwidth]{../fig/simulated_data.pdf}
\caption{{\bf Need caption.}
Need caption}
\label{fig:ivs}
\end{figure}


\begin{figure}[!ht]
\includegraphics[width=\textwidth]{../fig/true_effect.pdf}
\caption{{\bf Need caption.}
Need caption}
\label{fig:teff}
\end{figure}



\pagebreak

\bibliography{redqueen}
\end{document}
