
\documentclass[final]{beamer}

\usepackage[scale=1.4]{beamerposter} % Use the beamerposter package for laying out the poster

\usepackage[labelfont=bf]{caption}

\usepackage{wasysym}
\usetheme{confposter} % Use the confposter theme supplied with this template

\setbeamercolor{block title}{fg=ngreen,bg=white} % Colors of the block titles
\setbeamercolor{block body}{fg=black,bg=white} % Colors of the body of blocks
\setbeamercolor{block alerted title}{fg=white,bg=dblue!70} % Colors of the highlighted block titles
\setbeamercolor{block alerted body}{fg=black,bg=dblue!10} % Colors of the body of highlighted blocks
% Many more colors are available for use in beamerthemeconfposter.sty

%-----------------------------------------------------------
% Define the column widths and overall poster size
% To set effective sepwid, onecolwid and twocolwid values, first choose how many columns you want and how much separation you want between columns
% In this template, the separation width chosen is 0.024 of the paper width and a 4-column layout
% onecolwid should therefore be (1-(# of columns+1)*sepwid)/# of columns e.g. (1-(4+1)*0.024)/4 = 0.22
% Set twocolwid to be (2*onecolwid)+sepwid = 0.464
% Set threecolwid to be (3*onecolwid)+2*sepwid = 0.708

\newlength{\sepwid}
\newlength{\onecolwid}
\newlength{\twocolwid}
\newlength{\threecolwid}
\setlength{\paperwidth}{48in} % A0 width: 46.8in
\setlength{\paperheight}{36in} % A0 height: 33.1in
\setlength{\sepwid}{0.024\paperwidth} % Separation width (white space) between columns
\setlength{\onecolwid}{0.25\paperwidth} % Width of one column
\setlength{\twocolwid}{0.404\paperwidth} % Width of two columns
\setlength{\threecolwid}{0.708\paperwidth} % Width of three columns
\setlength{\topmargin}{-0.5in} % Reduce the top margin size
%-----------------------------------------------------------

\usepackage{graphicx}  % Required for including images

\usepackage{booktabs} % Top and bottom rules for tables

\newcommand{\etal}{\emph{et al.}}

%----------------------------------------------------------------------------------------
%	TITLE SECTION 
%----------------------------------------------------------------------------------------

\title{Quantifying the effects of parasites on the maintenance of sex} % Poster title

\author{Sang Woo Park and Ben Bolker} % Author(s)

\institute[McMaster University]{McMaster University, Hamilton, Ontario, Canada} % Institution(s)

%----------------------------------------------------------------------------------------

\begin{document}

\addtobeamertemplate{block end}{}{\vspace*{2ex}} % White space under blocks
\addtobeamertemplate{block alerted end}{}{\vspace*{2ex}} % White space under highlighted (alert) blocks

\setlength{\belowcaptionskip}{2ex} % White space under figures
\setlength\belowdisplayshortskip{2ex} % White space under equations

\begin{frame}[t] % The whole poster is enclosed in one beamer frame

\begin{columns}[t] % The whole poster consists of three major columns, the second of which is split into two columns twice - the [t] option aligns each column's content to the top

\begin{column}{\sepwid}\end{column} % Empty spacer column

\begin{column}{\onecolwid} % The first column

\begin{block}{Evolution of sex}
\begin{minipage}[c]{0.65\textwidth}
\begin{itemize}
    \setlength\itemsep{0.5em}
    \item \textbf{two modes of reproduction}:
    \begin{itemize}
        \setlength\itemsep{0.3em}
      \item \textbf{sexual} females require a male partner to produce an offspring
      \item \textbf{asexual} females produce offspring alone
    \end{itemize}
    \item sexual population grows slower because males cannot produce offspring; \textbf{why then do organisms reproduce sexually}?
\end{itemize}
\end{minipage}
\begin{minipage}[c]{0.34\textwidth}
\hfill
\includegraphics[width=0.9\textwidth]{cost.png}

{\tiny \hfill Gibson \etal\ \cite{gibson2017two}}
\end{minipage}
\end{block}

\begin{block}{Red Queen Hypothesis}
\vspace{-1em}
\begin{center}
\begin{figure}
\includegraphics[width=0.8\textwidth]{McKone.png}
\caption{The snail population in a New Zealand lake \cite{mckone2016fine} supports Lively's \cite{lively2001trematode} prediction of positive correlation between proportion male,  representing proportion of sexual snails, and
parasite prevalence (proportion of infected snails).}
\end{figure}
\end{center}
\vspace{-1em}
\begin{itemize}
\setlength\itemsep{0.4em}
    \item asexual and sexual snail populations (\emph{Potamopyrgus antipodarum}) coexist in New Zealand lakes
    \item snails are an important host for trematode parasites
    \item hypothesis: sexually reproducing snails $\to$ rare genotypes that resist trematode infection \cite{vergara2014infection} (the \textbf{Red Queen Hypothesis})
    \item Lively \cite{lively2001trematode} predicted that populations with more infection will have more sexual snails; \textbf{how likely is it to observe this trend in nature?}
\end{itemize}
\end{block}

%------------------------------------------------

% \begin{figure}
% \includegraphics[width=0.8\linewidth]{1.jpg}
% \caption{Graph of $f(x)=ax^2|_{\{0.1, 0.3, 1.0, 3.0\}}$}
% \end{figure}

%----------------------------------------------------------------------------------------

\end{column} % End of the first column

\begin{column}{\sepwid}\end{column} % Empty spacer column

\begin{column}{\twocolwid} % Begin a column which is two columns wide (column 2)

%----------------------------------------------------------------------------------------
%	MATERIALS
%----------------------------------------------------------------------------------------

\begin{block}{Methods}
\begin{minipage}[c]{0.48\textwidth}
\begin{enumerate}
\setlength\itemsep{0.3em}
    \item \ developed a mathematical model that represent the evolution of the snail population
    \begin{itemize} 
        \item each population is composed of both asexual ($A$) and sexual ($S$) hosts
        \item infected hosts can infect others
        \item hosts reproduce within their population but some can move to other populations
    \end{itemize}
    \item \ the model can generate ``data'' analogous to field observations
    \item \ identify parameters that make simulated data similar to observed data
\end{enumerate}
\end{minipage}
\begin{minipage}[c]{0.04\textwidth}
\end{minipage}
\begin{minipage}[c]{0.48\textwidth}
\begin{figure}
\includegraphics[width=\textwidth]{../fig/model_diagram.pdf}
\caption{Graphical representation of the model.}
\vspace{-1em}
\end{figure}
\vfill
\end{minipage}
\vspace{-1em}
\end{block}

%----------------------------------------------------------------------------------------
%----------------------------------------------------------------------------------------
%	IMPORTANT To REMEMBER
%----------------------------------------------------------------------------------------

\vskip 1cm

\begin{block}{Results}
\begin{figure}
\includegraphics[width=\textwidth]{../fig/simulated_data.pdf}
\caption{\textbf{Simulated ``data'' vs. observed data}. ($\triangle$) observations from a study site in one year ($\bigcirc$) proportion of sexual hosts and infected hosts in a simulated population averaged over 100 generations. 50 simulations are plotted; each simulation consists of 30 populations.}
\end{figure}
\vspace{-1em}
\begin{itemize}
    \item this model is not appropriate for studying the snail population in Israel (left panel; Dagan \etal\ \cite{dagan2013clonal}); need to consider other hypotheses for the maintenance of sex?
    \item when a population is dominated by asexual reproduction, stronger parasite infection leads to increase in sexual reproduction but decrease in proportion infected; opposite to Lively's prediction \cite{lively2001trematode}
    \item even stronger infection leads to a balance between sexual and asexual reproduction (hump at intermediate prevalence) and an eventual decrease in proportion of sexual reproduction
\end{itemize}
\end{block}

\end{column} % End of the second column

\begin{column}{\sepwid}\end{column} % Empty spacer column

\begin{column}{\onecolwid} % The third column

%----------------------------------------------------------------------------------------
%	CONCLUSION
%----------------------------------------------------------------------------------------

\begin{block}{Discussion}
\begin{figure}
\vspace{-1em}
\includegraphics[width=0.9\textwidth]{../fig/cycle_example.pdf}
\caption{\textbf{A closer look at Red Queen dynamics}. (left) interaction between parasites and sexual hosts drives various types of oscillations. (right) we expect to see a downward curved trend; averaging out oscillations in each population predicts an opposite trend}
\vspace{-1.5em}
\end{figure}
\begin{itemize}
    \item eventually parasites evolves to infect resistant snail and sexual reproduction decrease in the population; creates \textbf{oscillation between parasite and sexual population} (left panel)
\end{itemize}
\end{block}

\begin{alertblock}{Conclusion and further questions}
\vspace{0.05em}
\begin{itemize}
    \item sexual populations ``run away'' (to escape infection) from parasites but parasites ``chase'' (to infect more) sexual populations, creating an oscillation; depending on where the population is in the cycle, we can observe a wide range of trends
    \item what kind of data and tests are needed to detect oscillation in the population?
\end{itemize}
\end{alertblock}


%----------------------------------------------------------------------------------------
%	ACKNOWLEDGEMENTS
%----------------------------------------------------------------------------------------

\begin{block}{Reference}
{\tiny
%% Add numbered references
\setbeamertemplate{bibliography item}[text]
%% Stop line breaks
\setbeamertemplate{bibliography entry title}{}
\setbeamertemplate{bibliography entry location}{}
\setbeamertemplate{bibliography entry note}{}
\bibliographystyle{unsrt}
\bibliography{../misc/redqueen}
}
\end{block}


%----------------------------------------------------------------------------------------

\end{column} % End of the third column

\end{columns} % End of all the columns in the poster

\end{frame} % End of the enclosing frame

\end{document}
