
\documentclass[final]{beamer}

\usepackage[scale=1.24]{beamerposter} % Use the beamerposter package for laying out the poster

\usetheme{confposter} % Use the confposter theme supplied with this template

\setbeamercolor{block title}{fg=ngreen,bg=white} % Colors of the block titles
\setbeamercolor{block body}{fg=black,bg=white} % Colors of the body of blocks
\setbeamercolor{block alerted title}{fg=white,bg=dblue!70} % Colors of the highlighted block titles
\setbeamercolor{block alerted body}{fg=black,bg=dblue!10} % Colors of the body of highlighted blocks
% Many more colors are available for use in beamerthemeconfposter.sty

%-----------------------------------------------------------
% Define the column widths and overall poster size
% To set effective sepwid, onecolwid and twocolwid values, first choose how many columns you want and how much separation you want between columns
% In this template, the separation width chosen is 0.024 of the paper width and a 4-column layout
% onecolwid should therefore be (1-(# of columns+1)*sepwid)/# of columns e.g. (1-(4+1)*0.024)/4 = 0.22
% Set twocolwid to be (2*onecolwid)+sepwid = 0.464
% Set threecolwid to be (3*onecolwid)+2*sepwid = 0.708

\newlength{\sepwid}
\newlength{\onecolwid}
\newlength{\twocolwid}
\newlength{\threecolwid}
\setlength{\paperwidth}{48in} % A0 width: 46.8in
\setlength{\paperheight}{36in} % A0 height: 33.1in
\setlength{\sepwid}{0.024\paperwidth} % Separation width (white space) between columns
\setlength{\onecolwid}{0.22\paperwidth} % Width of one column
\setlength{\twocolwid}{0.464\paperwidth} % Width of two columns
\setlength{\threecolwid}{0.708\paperwidth} % Width of three columns
\setlength{\topmargin}{-0.5in} % Reduce the top margin size
%-----------------------------------------------------------

\usepackage{graphicx}  % Required for including images

\usepackage{booktabs} % Top and bottom rules for tables

\newcommand{\etal}{\emph{et al.}}


%----------------------------------------------------------------------------------------
%	TITLE SECTION 
%----------------------------------------------------------------------------------------

\title{Quantifying the effects of parasites on the maintenance of sex} % Poster title

\author{Sang Woo Park and Ben Bolker} % Author(s)

\institute[McMaster University]{McMaster University, Hamilton, Ontario, Canada} % Institution(s)

%----------------------------------------------------------------------------------------

\begin{document}

\addtobeamertemplate{block end}{}{\vspace*{2ex}} % White space under blocks
\addtobeamertemplate{block alerted end}{}{\vspace*{2ex}} % White space under highlighted (alert) blocks

\setlength{\belowcaptionskip}{2ex} % White space under figures
\setlength\belowdisplayshortskip{2ex} % White space under equations

\begin{frame}[t] % The whole poster is enclosed in one beamer frame

\begin{columns}[t] % The whole poster consists of three major columns, the second of which is split into two columns twice - the [t] option aligns each column's content to the top

\begin{column}{\sepwid}\end{column} % Empty spacer column

\begin{column}{\onecolwid} % The first column

\begin{alertblock}{Summary}
Why must \textbf{sexual reproduction} persist in nature given its \textbf{two-fold cost}? The \textbf{Red Queen Hypothesis} predicts sexually reproducing individuals to overcome the cost of sex by escaping infection more easily under strong parasite selection. Here, we tried to quantify the effect of the Red Queen and perform a power analysis.
\end{alertblock}

%----------------------------------------------------------------------------------------
%	QUICK REVISION
%----------------------------------------------------------------------------------------

\begin{block}{Evolution of sex}
\begin{itemize}
    \item \textbf{Two-fold cost of sex}: (1) cost of producing males and (2) cost of meiosis
    \item the two-fold cost of cost of sex asumes that \textbf{all else is equal}
    \item only 0.01\% eukaryotes conform to purely asexual reproduction. How?
\end{itemize}
\end{block}

\begin{block}{Red Queen Hypothesis}
\begin{figure}
\includegraphics[width=0.9\textwidth]{McKone.png}
\caption{Parasitism rate is positively correlated with male frequency \cite{mckone2016fine}.}
\vspace{-1em}
\end{figure}
\begin{itemize}
    \item sexual reproduction creates rare genotypes that can escape infection (\textbf{negative frequncy dependence})
    \item snail population in New Zealand (host for sterilizing trematode infection) is believed to support the hypothesis \cite{vergara2014infection}
    \item prevalence of sex should be \textbf{positively correlated} with prevalence of infection \cite{lively2001trematode}
    \item unable to detect any correlation in a similar snail-trematode system. Why? \cite{dagan2013clonal}
\end{itemize}
\end{block}

%------------------------------------------------

% \begin{figure}
% \includegraphics[width=0.8\linewidth]{1.jpg}
% \caption{Graph of $f(x)=ax^2|_{\{0.1, 0.3, 1.0, 3.0\}}$}
% \end{figure}

%----------------------------------------------------------------------------------------

\end{column} % End of the first column

\begin{column}{\sepwid}\end{column} % Empty spacer column

\begin{column}{\twocolwid} % Begin a column which is two columns wide (column 2)

\begin{columns}[t,totalwidth=\twocolwid] % Split up the two columns wide column

\begin{column}{\onecolwid}\vspace{-.6in} % The first column within column 2 (column 2.1)

%----------------------------------------------------------------------------------------
%	MATERIALS
%----------------------------------------------------------------------------------------

\begin{block}{Mathematical model}
\begin{figure}
\includegraphics[width=0.9\textwidth]{../fig/model_diagram.pdf}
\caption{Graphical representation of the model. Double lined arrows represent dynamics that are affected by mixing betwee habitats.}
\vspace{-1em}
\end{figure}
\begin{itemize}
    \item competition between obligate sexual ($S$) and clonal ($A$) population under parasite selection is represented by a mathematical model \cite{lively2010epidemiological}
    \item hosts stay within their habitats and can mix with hosts in different habitats
    \item varying transmission rates across habitats
    \item relies on stochastic computer simulations
\end{itemize}
\end{block}

%----------------------------------------------------------------------------------------

\end{column} % End of column 2.1

\begin{column}{\onecolwid}\vspace{-.6in} % The second column within column 2 (column 2.2)

%----------------------------------------------------------------------------------------
%	
%----------------------------------------------------------------------------------------

\begin{block}{Approximate Bayesian Computation (ABC)}
\begin{itemize}
    \item a random sample of parameters is drawn
    \item simulated data is compared to the observed data
    \item if the difference is small enough, the parameter sample that generated the data is \emph{accepted}
    \item repeated until enough sample is obtained
\end{itemize}
\begin{figure}
\includegraphics[width=1\textwidth]{../fig/smc_param_red.pdf}
\caption{(black) prior distributions where parameters sampled from and (red) posterior distributions obtained from ABC}
\end{figure}
\end{block}

%----------------------------------------------------------------------------------------

\end{column} % End of column 2.2

\end{columns} % End of the split of column 2 - any content after this will now take up 2 columns width

%----------------------------------------------------------------------------------------
%	IMPORTANT To REMEMBER
%----------------------------------------------------------------------------------------

\begin{block}{Results}
\begin{minipage}[c]{0.5\textwidth}
\begin{figure}
\includegraphics[width=0.9\textwidth]{../fig/simulated_data.pdf}
\caption{Simulated data v.s. observed data. Each point represents mean proportion infected and sexual at each site.}
\end{figure}
\end{minipage}
\begin{minipage}[c]{0.5\textwidth}
\begin{itemize}
    \item fitted result does not match Dagan \etal\ \cite{dagan2013clonal}
    \item overestimates proportion infected when fitted to McKone \etal\ \cite{mckone2016fine}
    \item spatial structure allows high level of infection to be maintained even at high virulence (middle panel)
    \item initially increasing prevalence of sexual reproduction pulls back infection (consistent with \cite{lively2001trematode}) and causes prevalence of infection to decrease; quadratic overall?
\end{itemize}
\end{minipage}
\begin{minipage}[c]{0.35\textwidth}
\begin{itemize}
    \item better to increase number of sites than number of samples
    \item Spearman's rank correlation has higher power for detecting a positive correlation than Pearson correlation
    \item a negative correlation is observed from simulated data fitted to Vergara \etal\
    \item very low power for detecting a negative quadratic curvature
\end{itemize}
\vfill
\end{minipage}
\begin{minipage}[c]{0.65\textwidth}
\vspace*{20px}
\begin{figure}
\includegraphics[width=1\textwidth]{../fig/power.pdf}
\caption{Power analysis for detecting a correlation and negative quadratic curvature.}
\end{figure}
\end{minipage}
\end{block} 

\end{column} % End of the second column

\begin{column}{\sepwid}\end{column} % Empty spacer column

\begin{column}{\onecolwid} % The third column

%----------------------------------------------------------------------------------------
%	CONCLUSION
%----------------------------------------------------------------------------------------

\begin{block}{Discussion}
\begin{figure}
\includegraphics[width=\textwidth]{../fig/cycle_example.pdf}
\caption{A sample data from a posterior sample. (left) type of cycles present in a simulated data (right) observed relationship v.s. expected relationship. (dashed line) quadratic regression.}
\vspace{-1em}
\end{figure}
\begin{itemize}
    \item "expected effect" is masked by different cycles (explains low power)
    \item high asexual diversity \cite{dagan2013clonal} and different environment (e.g., seasonal flood \cite{ben2007temporal} and highly interconnected but diverse \cite{dagan2013clonal}) may not be appropriate for the Red Queen Hypothesis?
    \item unusual sampling problems in nature (\cite{vergara2014infection} v.s. \cite{vergara2013geographic})
\end{itemize}
\end{block}

\begin{alertblock}{Conclusion and further questions}
\begin{itemize}
    \item spatial data provides limited information; only Vergara \etal\ \cite{vergara2014infection} had spatiotemporal data
    \item is there a way to detect the Red Queen cycles from a spatiotemporal data?
    \item consider pluralistic approach (Red Queen hypothesis + other mechanisms for maintaining sex)
\end{itemize}
\end{alertblock}


%----------------------------------------------------------------------------------------
%	ACKNOWLEDGEMENTS
%----------------------------------------------------------------------------------------

\begin{block}{Reference}
{\tiny
%% Add numbered references
\setbeamertemplate{bibliography item}[text]
%% Stop line breaks
\setbeamertemplate{bibliography entry title}{}
\setbeamertemplate{bibliography entry location}{}
\setbeamertemplate{bibliography entry note}{}
\bibliographystyle{unsrt}
\bibliography{../misc/redqueen}
}
\end{block}


%----------------------------------------------------------------------------------------

\end{column} % End of the third column

\end{columns} % End of all the columns in the poster

\end{frame} % End of the enclosing frame

\end{document}
